# Spring boot application
spring:
  application:
    name: myshop-service-upload
  thymeleaf:
    cache: false # 开发时关闭缓存,不然没法看到实时页面
    mode: LEGACYHTML5 # 用非严格的 HTML
    encoding: UTF-8
    servlet:
      content-type: text/html
server:
  port: 8602

# Services Versions
services:
  versions:
    upload:
      v1: 1.0.0

fastdfs.base.url: http://120.24.200.204:8888/
storage:
  type: fastdfs
  fastdfs:
    tracker_server: 120.24.200.204:22122