version: '3.1'
services:
  myshop-service-user-consumer:
    restart: always
    container_name: myshop-service-user-consumer
    image: 127.0.0.1:5000/myshop-service-user-consumer
    ports:
      - 8601:8601
      - 8701:8701
      - 30881:30881
    networks:
    - service-user-network

networks:
  default:
    external:
      name: service-user-network