version: '3.1'
services:
  myshop-service-user-provider:
    restart: always
    container_name: myshop-service-user-provider
    image: 127.0.0.1:5000/myshop-service-user-provider
    ports:
      - 8501:8501
      - 22222:22222
      - 20881:20881
    networks:
    - service-user-network

networks:
  service-user-network: