# Spring boot application
spring:
  application:
    name: myshop-api-gateway
  thymeleaf:
    cache: false # 开发时关闭缓存,不然没法看到实时页面
    mode: LEGACYHTML5 # 用非严格的 HTML
    encoding: UTF-8
    servlet:
      content-type: text/html
server:
  port: 9000

# Services Versions
services:
  ports:
    user: 8601
    upload: 8602
    redis: 8603
    search: 8604
  versions:
    user:
      v1: 1.0.0
    search:
      v1: 1.0.0
    redis:
      v1: 1.0.0
    upload:
      v1: 1.0.0

# Dubbo Config properties
dubbo:
  scan:
    basePackages: com.evan.myshop.api.gateway.controller
  ## ApplicationConfig Bean
  application:
    id: myshop-api-gateway
    name: myshop-api-gateway
  ## ProtocolConfig Bean
  protocol:
    id: dubbo
    name: dubbo
    serialization: kryo
  ## RegistryConfig Bean
  registry:
    id: zookeeper
    address: zookeeper://120.24.200.204:2181

# Dubbo Endpoint (default status is disable)
endpoints:
  dubbo:
    enabled: true

management:
  server:
    port: 9001
  # Dubbo Health
  health:
    dubbo:
      status:
        ## StatusChecker Name defaults (default : "memory", "load" )
        defaults: memory
  # Enables Dubbo All Endpoints
  endpoint:
    dubbo:
      enabled: true
    dubbo-shutdown:
      enabled: true
    dubbo-configs:
      enabled: true
    dubbo-services:
      enabled: true
    dubbo-references:
      enabled: true
    dubbo-properties:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"