version: '3.1'
services:
  myshop-service-search-consumer:
    restart: always
    container_name: myshop-service-search-consumer
    image: 127.0.0.1:5000/myshop-service-search-consumer
    ports:
      - 8604:8604
      - 30884:30884
      - 8704:8704
    networks:
    - service-search-network

networks:
  default:
    external:
      name: service-search-network